trigger:
  - master

variables:
  - group: Tokens

resources:
  containers:
    - container: linux
      image: chillicream/dotnet-build:3.0

jobs:
  - job: release
    container: linux
    steps:
      - script: ./build.sh -target=release
        env:
          Sonar_Pr_Key: $(System.PullRequest.PullRequestNumber)
          Sonar_Branch: $(System.PullRequest.SourceBranch)
        displayName: build
