trigger:
  - refs/tags/*

pr:
  - master

variables:
  - group: Tokens

jobs:
  - job: pr
    condition: eq(True, variables['System.PullRequest.PullRequestNumber'])
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: bash ./build.sh -target=release
        env:
          Sonar_Pr_Key: $(System.PullRequest.PullRequestNumber)
          Sonar_Branch: $(System.PullRequest.SourceBranch)
        displayName: build

  - job: release
    condition: and(contains(variables['Build.SourceBranch'], 'refs/tags/'), eq(False, variables['System.PullRequest.PullRequestNumber']))
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: bash ./build.sh -target=release
        env:
          Version: $(Build.SourceBranchName)
        displayName: build
      - script: bash ./build.sh -target=push
        displayName: publish
