trigger:
  - master

pr:
  - master

variables:
  - group: Tokens

jobs:
  - job: pr
    condition: ne(variables['System.PullRequest.PullRequestNumber'], Null)
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: bash ./build.sh -target=release
        env:
          Sonar_Pr_Key: $(System.PullRequest.PullRequestNumber)
          Sonar_Branch: $(System.PullRequest.SourceBranch)
        displayName: build

  - job: release
    condition: eq(variables['System.PullRequest.PullRequestNumber'], Null)
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: bash ./build.sh -target=release
        displayName: build
      - script: bash ./build.sh -target=push
        displayName: publish
