trigger:
  - refs/tags/*

pr:
  - master

variables:
  - group: Tokens

jobs:
  - job: pull_request_build
    displayName: Pull Request Build
    condition: eq(True, variables['System.PullRequest.PullRequestNumber'])
    pool:
      vmImage: ubuntu-16.04
    steps:
      - bash: ./build.sh -target=sonar
        env:
          Sonar_Token: $(Sonar_Token)
          Sonar_Pr_Key: $(System.PullRequest.PullRequestNumber)
          Sonar_Branch: $(System.PullRequest.SourceBranch)
        displayName: Sonar Build

  - job: release_build
    displayName: Release Build
    condition: and(contains(variables['Build.SourceBranch'], 'refs/tags/'), eq(False, variables['System.PullRequest.PullRequestNumber']))
    pool:
      vmImage: ubuntu-16.04
    steps:
      - bash: ./build.sh -target=sonar
        env:
          Sonar_Token: $(Sonar_Token)
          Version: $(Build.SourceBranchName)
        displayName: Sonar Build
      - bash: ./build.sh -target=publish
        env:
          Version: $(Build.SourceBranchName)
        displayName: Create Artifacts
      - bash: ./build.sh -target=push
        env:
          Nuget_Token: $(Nuget_Token)
        displayName: Publish Packages
